-- /config/setup/rag_user.sql
-- Run this script using a superuser account (e.g., psql -U postgres -f rag_user.sql)

-- --- CONFIGURATION ---
\set RAG_USER 'rag_user'
\set RAG_PASS 'wrinklepants'
\set RAG_DB 'rag_db'
\set METADATA_DB 'metadata_catalog'

-- 1. CREATE THE USER/ROLE
CREATE USER :RAG_USER WITH ENCRYPTED PASSWORD :'RAG_PASS' LOGIN;

-- 2. CREATE THE DATABASES
CREATE DATABASE :RAG_DB OWNER :RAG_USER ENCODING 'UTF8';
CREATE DATABASE :METADATA_DB OWNER :RAG_USER ENCODING 'UTF8';

-- 3. GRANT CONNECT AND PRIVILEGES
GRANT CONNECT ON DATABASE :RAG_DB TO :RAG_USER;
GRANT ALL PRIVILEGES ON DATABASE :RAG_DB TO :RAG_USER;

GRANT CONNECT ON DATABASE :METADATA_DB TO :RAG_USER;
GRANT ALL PRIVILEGES ON DATABASE :METADATA_DB TO :RAG_USER;

ALTER USER :RAG_USER CREATEDB;

-- 4. APPLY DEFAULT PRIVILEGES
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO :RAG_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO :RAG_USER;

-- Confirmation
SELECT 'User ' || :'RAG_USER' || ' created with databases: ' || :'RAG_DB' || ', ' || :'METADATA_DB' AS status;